### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Mayankkatheriya** [oktayshakirov/portfolio#1]
hey!
there is a suggestion for your portfolio
on selection of text backgroundcolor is set to the orange and text color is white , this results that text is not visible properly
if you want i can contribute in your portfolio with some CSS and some more js effects

**Comment by oktayshakirov** [comment]
Hey, thanks for pointing out. I never noticed. I can fix it when i have some time. If you want to contribute, feel free to play with it, but is not necessary. Thanks !

**Comment by Mayankkatheriya** [comment]
ok thank you, i will update you soon

**Comment by oktayshakirov** [comment]
Thanks for the pull request. Appreciated !
